version: '3.3'
services:

  postgres:
    container_name: foodgram-postgres
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    container_name: foodgram-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
      - ../data:/app/data
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata data/ingredients.json &&
             gunicorn foodgram_backend.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
